function labelkey = getLabelKey()
  labelkey = {
    'beverages', 
    'bread', 
    'cereal', 
    'cheese', 
    'counter', 
    'dairy', 
    'entrance', 
    'flowers', 
    'frozenfood', 
    'health', 
    'meat', 
    'oils', 
    'pasta', 
    'snacks', 
    'vegetables', 
    'water', 
    'none',
    'toiletries',
    'tea_coffee',
    'ready_to_eat',
    'sauce',
    'soup',
    'pets',
    'candy',
    'canned_food'
  };
end
